QAServices/Accuracx/Controllers/AdminProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DBHandler.Model;
using DBHandler.DataContexts;
using JiraIntegration.JIRAImpl;
using DBHandler.EntityFrameWorkImpl;

namespace Accuracx.Controllers
{
    public class AdminProjectController : Controller
    {
        private QAServices db = new QAServices();

        //
        // GET: /AdminProject/

        public ActionResult AdminDashBoard()
        {
            EFProjectImpl projectImpl = DBHandler.EntityFrameWorkImpl.EFImplObjectManager.CreateEFProjectImplObject();
            var list = projectImpl.GetProjectList();
            return View(list);
        }

        //
        // GET: /AdminProject/Details/5

        public ActionResult Details(int id = 0)
        {
            EFProjectImpl projectImpl = DBHandler.EntityFrameWorkImpl.EFImplObjectManager.CreateEFProjectImplObject();
            var project = projectImpl.FindProject(id);
            if (project == null)
            {
                return HttpNotFound();
            }

            string projectStatus = string.Empty;
            ViewBag.ClientMessage = "Pay the installemt";

            if (project.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.Submitted)
            {
                ViewBag.ProjectStatus = DBHandler.Common.CommonEnums.ProjectStatus.Submitted.ToString();
                return View("SubmittedProjectDetails", project);
            }
            else if (project.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.OnGoing)
            {
                projectStatus = DBHandler.Common.CommonEnums.ProjectStatus.OnGoing.ToString();
            }
            else if (project.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.Complete)
            {
                projectStatus = DBHandler.Common.CommonEnums.ProjectStatus.Submitted.ToString();
            }

            ViewBag.ProjectStatus = projectStatus;

            return View(project);
        }

        public ActionResult AddNewQuotation(string estimation, string budget, string notes, string id)
        {
            try
            {
                EFProjectImpl projectImpl = DBHandler.EntityFrameWorkImpl.EFImplObjectManager.CreateEFProjectImplObject();
                Quotation quotation = new Quotation {Estimation=Convert.ToInt32(estimation),Budget=Convert.ToDecimal(budget),Notes=notes };
                var result = projectImpl.AddQuotation(Convert.ToInt32(id), quotation);
                return Json(new { result = true }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception)
            {
                return Json(new { result = false }, JsonRequestBehavior.AllowGet);
            }
        }

        //public ActionResult GetQuotationDetails(int projectId)
        //{
        //    try
        //    {
        //        EFProjectImpl projectImpl = DBHandler.EntityFrameWorkImpl.EFImplObjectManager.CreateEFProjectImplObject();
        //        Quotation quotation = new Quotation { Estimation = Convert.ToInt32(estimation), Budget = Convert.ToDecimal(budget), Notes = notes };
        //        var result = projectImpl.AddQuotation(Convert.ToInt32(id), quotation);
        //        return Json(new { result = true }, JsonRequestBehavior.AllowGet);

        //    }
        //    catch (Exception)
        //    {
        //        return Json(new { result = false }, JsonRequestBehavior.AllowGet);
        //    }
        //}

        //
        // GET: /AdminProject/Create

        public ActionResult Create()
        {
            ViewBag.ProjectTypeId = new SelectList(db.ProjectTypes, "ProjectTypeId", "ProjectTypeName");
            ViewBag.PaymentPlanId = new SelectList(db.PaymentPlans, "PaymentPlanId", "PaymentPlanName");
            ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName");
            ViewBag.QuotationId = new SelectList(db.Quotations, "QuotationId", "Notes");
            return View();
        }

        //
        // POST: /AdminProject/Create

        //[HttpPost]
        //public ActionResult Create(Project project)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Projects.Add(project);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.ProjectTypeId = new SelectList(db.ProjectTypes, "ProjectTypeId", "ProjectTypeName", project.ProjectTypeId);
        //    ViewBag.PaymentPlanId = new SelectList(db.PaymentPlans, "PaymentPlanId", "PaymentPlanName", project.PaymentPlanId);
        //    ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName", project.UserId);
        //    ViewBag.QuotationId = new SelectList(db.Quotations, "QuotationId", "Notes", project.QuotationId);
        //    return View(project);
        //}

        //
        // GET: /AdminProject/Edit/5

        //public ActionResult Edit(int id = 0)
        //{
        //    Project project = db.Projects.Find(id);
        //    if (project == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.ProjectTypeId = new SelectList(db.ProjectTypes, "ProjectTypeId", "ProjectTypeName", project.ProjectTypeId);
        //    ViewBag.PaymentPlanId = new SelectList(db.PaymentPlans, "PaymentPlanId", "PaymentPlanName", project.PaymentPlanId);
        //    ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName", project.UserId);
        //    ViewBag.QuotationId = new SelectList(db.Quotations, "QuotationId", "Notes", project.QuotationId);
        //    return View(project);
        //}

        //
        // POST: /AdminProject/Edit/5

        //[HttpPost]
        //public ActionResult Edit(Project project)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(project).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ProjectTypeId = new SelectList(db.ProjectTypes, "ProjectTypeId", "ProjectTypeName", project.ProjectTypeId);
        //    ViewBag.PaymentPlanId = new SelectList(db.PaymentPlans, "PaymentPlanId", "PaymentPlanName", project.PaymentPlanId);
        //    ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName", project.UserId);
        //    ViewBag.QuotationId = new SelectList(db.Quotations, "QuotationId", "Notes", project.QuotationId);
        //    return View(project);
        //}

        //
        // GET: /AdminProject/Delete/5

        //public ActionResult Delete(int id = 0)
        //{
        //    Project project = db.Projects.Find(id);
        //    if (project == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(project);
        //}

        //
        // POST: /AdminProject/Delete/5

        [HttpPost, ActionName("Delete")]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Project project = db.Projects.Find(id);
        //    db.Projects.Remove(project);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

QAServices/Accuracx/Views/AdminProject/AdminDashBoard.cshtml
@model IEnumerable<DBHandler.Model.Project>
@using GridMvc.Html

@{
    ViewBag.Title = "Listings";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<h2>@ViewBag.Title</h2>
<div class="clear-fix">&nbsp;</div>

<label>submited projects</label>@Model.Where(p => p.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.Submitted).Count();

<label>On going projects</label>@Model.Where(p => p.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.OnGoing).Count();

<label>Comleted  projects</label>@Model.Where(p => p.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.Complete).Count();

<label>New Bug Reports</label>@Model.Where(p => p.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.Complete).Count();

<label>Messages</label>@Model.Where(p => p.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.Complete).Count();

<h1>Submitted Projects</h1>

@Html.Grid(Model.Where(p=>p.StatusId==(int)DBHandler.Common.CommonEnums.ProjectStatus.Submitted)).Columns(columns =>
          {
              columns.Add(t => t.ProjectName).Titled("Project Name").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.ProjectType.ProjectTypeName).Titled("Project Type").SetWidth(120).Sortable(true).Filterable(true);

              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("View", "Details", "AdminProject", new { id = o.ProjectId, page = ViewBag.Page }, new { @class = "btn btn-info modal-link" }).ToHtmlString());

          }).WithPaging(10)

<h1>Ongoing Projects</h1>

@Html.Grid(Model.Where(p=>p.StatusId==(int)DBHandler.Common.CommonEnums.ProjectStatus.OnGoing)).Columns(columns =>
          {
              columns.Add(t => t.ProjectName).Titled("Project Name").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.ProjectType.ProjectTypeName).Titled("Project Type").SetWidth(120).Sortable(true).Filterable(true);

              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("View", "Details", "AdminProject", new { id = o.ProjectId, page = ViewBag.Page }, new { @class = "btn btn-info modal-link" }).ToHtmlString());

          }).WithPaging(10)

<h1>Completed Projects</h1>

@Html.Grid(Model.Where(p=>p.StatusId==(int)DBHandler.Common.CommonEnums.ProjectStatus.Complete)).Columns(columns =>
          {
              columns.Add(t => t.ProjectName).Titled("Project Name").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.ProjectType.ProjectTypeName).Titled("Project Type").SetWidth(120).Sortable(true).Filterable(true);

              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("View", "Details", "AdminProject", new { id = o.ProjectId, page = ViewBag.Page }, new { @class = "btn btn-info modal-link" }).ToHtmlString());

          }).WithPaging(10)

QAServices/Accuracx/Views/AdminProject/Create.cshtml
@model DBHandler.Model.Project

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Project</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectTypeId, "ProjectType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ProjectTypeId", String.Empty)
            @Html.ValidationMessageFor(model => model.ProjectTypeId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProjectName)
            @Html.ValidationMessageFor(model => model.ProjectName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Features)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Features)
            @Html.ValidationMessageFor(model => model.Features)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HardwareReq)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HardwareReq)
            @Html.ValidationMessageFor(model => model.HardwareReq)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SoftwareReq)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SoftwareReq)
            @Html.ValidationMessageFor(model => model.SoftwareReq)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Limitations)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Limitations)
            @Html.ValidationMessageFor(model => model.Limitations)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DocumentPath)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DocumentPath)
            @Html.ValidationMessageFor(model => model.DocumentPath)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StatusId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StatusId)
            @Html.ValidationMessageFor(model => model.StatusId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PaymentPlanId, "PaymentPlan")
        </div>
        <div class="editor-field">
            @Html.DropDownList("PaymentPlanId", String.Empty)
            @Html.ValidationMessageFor(model => model.PaymentPlanId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId, "User")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.QuotationId, "Quotation")
        </div>
        <div class="editor-field">
            @Html.DropDownList("QuotationId", String.Empty)
            @Html.ValidationMessageFor(model => model.QuotationId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectUrl)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProjectUrl)
            @Html.ValidationMessageFor(model => model.ProjectUrl)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QAServices/Accuracx/Views/AdminProject/Delete.cshtml
@model DBHandler.Model.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Project</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProjectType.ProjectTypeName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectType.ProjectTypeName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProjectName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Features)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Features)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HardwareReq)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HardwareReq)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SoftwareReq)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SoftwareReq)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Limitations)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Limitations)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DocumentPath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DocumentPath)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.StatusId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StatusId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PaymentPlan.PaymentPlanName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PaymentPlan.PaymentPlanName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Quotation.Notes)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quotation.Notes)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProjectUrl)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectUrl)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

QAServices/Accuracx/Views/AdminProject/Details.cshtml
@model DBHandler.Model.Project

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Project</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProjectType.ProjectTypeName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectType.ProjectTypeName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProjectName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Features)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Features)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HardwareReq)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HardwareReq)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SoftwareReq)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SoftwareReq)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Limitations)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Limitations)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DocumentPath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DocumentPath)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.StatusId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StatusId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PaymentPlan.PaymentPlanName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PaymentPlan.PaymentPlanName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Quotation.Notes)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quotation.Notes)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProjectUrl)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectUrl)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ProjectId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QAServices/Accuracx/Views/AdminProject/SubmittedProjectDetails.cshtml
@model DBHandler.Model.Project

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<script>
    $(function () {

        function CloseQuot() {
            $('#estimation').val('');
            $('#budget').val('');
            $('#notes').val('');
            $('.login-box').animate({ 'top': '-165px' }, 500);
            $('.login-frame').fadeOut(500);
        }

        function OpenQuot() {
            $('.login-frame').fadeIn(500);
            $('.login-box').animate({ 'top': '100px' }, 500);
        }

        function OpenUpdateQuot() {
            var projectId = '@Model.ProjectId';
            $('#estimation').val('@Model.Quotation.Estimation');
            $('#budget').val('@Model.Quotation.Budget');
            $('#notes').val('@Model.Quotation.Notes');
            $('.login-frame').fadeIn(500);
            $('.login-box').animate({ 'top': '100px' }, 500);
        }

        $(document).on('click', '#addQuot', function (e) {
            OpenQuot();
            e.preventDefault();
        });

        $(document).on('click', '#updateQuot', function (e) {
            OpenUpdateQuot();
            e.preventDefault();
        });

        $(document).on('click', '#btn_close', function (e) {
            CloseQuot();
            e.preventDefault();
        });

        $(document).on('click', '#btn_save', function (e) {
            var estimation = $('#estimation').val();
            var budget = $('#budget').val();
            var notes = $('#notes').val();
            var _loginMsg = $('#msg');
            if (estimation == '' || budget == '') {
                _loginMsg.addClass("error").removeClass("success");
                _loginMsg.html("Fields should not be empty");
                $('.login-box')
                         .animate({ left: -25 }, 20)
                         .animate({ left: 0 }, 60)
                         .animate({ left: 25 }, 20)
                         .animate({ left: 0 }, 60);
            } else {
                var Objdata = {};
                Objdata.estimation = estimation;
                Objdata.budget = budget;
                Objdata.notes = notes;
                Objdata.id = '@Model.ProjectId';
                alert(Objdata.id);
                var url = "@Url.Action("AddNewQuotation", "AdminProject")";
                $.ajax({
                    type: "POST",
                    url: url,
                    data: JSON.stringify(Objdata),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",

                    success: function (response) {
                        alert('sucess');
                        if (response.result == true) {
                            _loginMsg.addClass("success").removeClass("error");
                            _loginMsg.html("Login was successful!");
                            $('.login-box').animate({ 'top': '-165px' }, 800);
                            $('.login-frame').fadeOut(500);
                            var url = '../Details?id=' + Objdata.id;

                            $(location).attr('href', url);

                        } else {
                            _loginMsg.addClass("error").removeClass("success");
                            _loginMsg.html("Invalid username & Password");
                            $('.login-box')
                                 .animate({ left: -25 }, 20)
                                 .animate({ left: 0 }, 60)
                                 .animate({ left: 25 }, 20)
                                 .animate({ left: 0 }, 60);
                            $('#estimation').val("");
                            $('#budget').val("");
                            $('#notes').val("");
                        }
                    },
                    error: function (xmlHttpRequest, textStatus, errorThrown) {

                        alert('fail');
                        alert(xmlHttpRequest.toString());
                        alert(textStatus);
                        alert(errorThrown);
                        alert('Error');
                    }
                });
            }

            e.preventDefault();
        });
    });
</script>


<h2>@ViewBag.Title</h2>
<div class="clear-fix">&nbsp;</div>

@Html.DisplayFor(model => model.ProjectName)

@Html.Label((String)ViewBag.ProjectStatus)

@Html.ActionLink("Notifications", "Index")

@if (Model.Quotation == null)
{
    <a id="addQuot">Add Qutation</a>
}
else if (Model.Quotation.Approved == false)
{
    <a id="updateQuot">Update Qutation</a>
}

@if (Model.Quotation != null)
{
    <h6>Quotation Details</h6>
    <label>Estimation</label>
    <label>@Model.Quotation.Estimation</label>
    <label>Budget</label>
    <label>@Model.Quotation.Budget</label>
    <label>Satus</label>
    if (Model.Quotation.Approved)
    {
        <label>Quotation Approved</label>
    }
    else
    {
        <label>Quotation Not Approved Yet</label>
    }

}

<div class="display-label">
    @Html.DisplayNameFor(model => model.ProjectType.ProjectTypeName)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.ProjectType.ProjectTypeName)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.Description)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Description)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.Features)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Features)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.HardwareReq)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.HardwareReq)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.SoftwareReq)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.SoftwareReq)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.Limitations)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Limitations)
</div>

<form id="form1" runat="server">
    <div>
        <div class="login-frame">
            <div class="login-box">
                <div id="msg"></div>
                <div class="form-group">
                    <label class="form-label">Estimation:</label>
                    <input id="estimation" runat="server" cssclass="form-control" />
                </div>
                <div class="form-group">
                    <label class="form-label">Budget:</label>
                    <input id="budget" class="form-control" />
                </div>
                <div class="form-group">
                    <label class="form-label">Notes:</label>
                    <input id="notes" class="form-control"/>
                </div>
                <div class="login-actions">
                    <button id="btn_save" runat="server" text="Save" class="btn login-btn" />
                    <button id="btn_close" runat="server" text="Cancel" class="btn close-login" />
                </div>
            </div>
        </div>
    </div>
</form>

<div>
    @Html.ActionLink("Back to List", "AdminDashBoard")
</div>