QAServices/Accuracx/Controllers/UserProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DBHandler.Model;
using DBHandler.DataContexts;
using DBHandler.EntityFrameWorkImpl;
using DBHandler.Common;
using WebMatrix.WebData;

namespace Accuracx.Controllers
{
    [Authorize(Roles = "User")]
    public class UserProjectController : Controller
    {

        //
        // GET: /UserProject/



        //public ActionResult Index()
        //{
        //    //var projects = db.Projects.Include(p => p.ProjectType).Include(p => p.PaymentPlan).Include(p => p.User).Include(p => p.Quotation);
        //    //return View(projects.ToList());
        //}

        public ActionResult DashBoard()
        {
            int userId = WebSecurity.GetUserId(User.Identity.Name);
            EFProjectImpl projectImpl = DBHandler.EntityFrameWorkImpl.EFImplObjectManager.CreateEFProjectImplObject();
            var list = projectImpl.GetProjectList(userId);
            return View(list);
        }

        //
        // GET: /UserProject/Details/5

        public ActionResult Details(int id = 0)
        {
            EFProjectImpl projectImpl = DBHandler.EntityFrameWorkImpl.EFImplObjectManager.CreateEFProjectImplObject();
            var project = projectImpl.FindProject(id);
            if (project == null)
            {
                return HttpNotFound();
            }

            string projectStatus = string.Empty;
            ViewBag.ClientMessage = "Pay the installemt";

            if (project.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.Submitted)
            {
                ViewBag.ProjectStatus = DBHandler.Common.CommonEnums.ProjectStatus.Submitted.ToString();
                return View("SubmittedProjectDetails", project);
            }
            else if (project.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.OnGoing)
            {
                projectStatus = DBHandler.Common.CommonEnums.ProjectStatus.OnGoing.ToString();
            }
            else if (project.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.Complete)
            {
                projectStatus = DBHandler.Common.CommonEnums.ProjectStatus.Submitted.ToString();
            }

            ViewBag.ProjectStatus = projectStatus;

            return View(project);
        }

        //
        // GET: /UserProject/Create

        public ActionResult Create()
        {
            EFProjectImpl projectImpl = DBHandler.EntityFrameWorkImpl.EFImplObjectManager.CreateEFProjectImplObject();
            var projectTypes = projectImpl.GetProjectTypeList();

            ViewBag.ProjectTypeId = new SelectList(projectTypes, "ProjectTypeId", "ProjectTypeName");
            return View();
        }

        //
        // POST: /UserProject/Create

        [HttpPost]
        public ActionResult Create(Project project)
        {
            EFProjectImpl projectImpl = DBHandler.EntityFrameWorkImpl.EFImplObjectManager.CreateEFProjectImplObject();

            if (ModelState.IsValid)
            {
                project.StatusId = (int)CommonEnums.ProjectStatus.Submitted;
                int userId = WebSecurity.GetUserId(User.Identity.Name);
                project.UserId = userId;
                var result = projectImpl.SaveProject(project);
                return RedirectToAction("DashBoard");
            }

            var projectTypes = projectImpl.GetProjectTypeList();
            ViewBag.ProjectTypeId = new SelectList(projectTypes, "ProjectTypeId", "ProjectTypeName", project.ProjectTypeId);
            return View(project);
        }

        ////
        //// GET: /UserProject/Edit/5

        //public ActionResult Edit(int id = 0)
        //{
        //    Project project = db.Projects.Find(id);
        //    if (project == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.ProjectTypeId = new SelectList(db.ProjectTypes, "ProjectTypeId", "ProjectTypeName", project.ProjectTypeId);
        //    ViewBag.PaymentPlanId = new SelectList(db.PaymentPlans, "PaymentPlanId", "PaymentPlanName", project.PaymentPlanId);
        //    ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName", project.UserId);
        //    ViewBag.QuotationId = new SelectList(db.Quotations, "QuotationId", "Notes", project.QuotationId);
        //    return View(project);
        //}

        ////
        //// POST: /UserProject/Edit/5

        //[HttpPost]
        //public ActionResult Edit(Project project)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(project).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ProjectTypeId = new SelectList(db.ProjectTypes, "ProjectTypeId", "ProjectTypeName", project.ProjectTypeId);
        //    ViewBag.PaymentPlanId = new SelectList(db.PaymentPlans, "PaymentPlanId", "PaymentPlanName", project.PaymentPlanId);
        //    ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName", project.UserId);
        //    ViewBag.QuotationId = new SelectList(db.Quotations, "QuotationId", "Notes", project.QuotationId);
        //    return View(project);
        //}

        ////
        //// GET: /UserProject/Delete/5

        //public ActionResult Delete(int id = 0)
        //{
        //    Project project = db.Projects.Find(id);
        //    if (project == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(project);
        //}

        ////
        //// POST: /UserProject/Delete/5

        //[HttpPost, ActionName("Delete")]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Project project = db.Projects.Find(id);
        //    db.Projects.Remove(project);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    db.Dispose();
        //    base.Dispose(disposing);
        //}
    }
}

QAServices/Accuracx/Views/UserProject/BasicProjectDetails.cshtml
@model DBHandler.Model.Project

QAServices/Accuracx/Views/UserProject/Create.cshtml
 @model DBHandler.Model.Project

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Project</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectTypeId, "ProjectType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ProjectTypeId", String.Empty)
            @Html.ValidationMessageFor(model => model.ProjectTypeId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProjectName)
            @Html.ValidationMessageFor(model => model.ProjectName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Features)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Features)
            @Html.ValidationMessageFor(model => model.Features)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HardwareReq)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HardwareReq)
            @Html.ValidationMessageFor(model => model.HardwareReq)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SoftwareReq)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SoftwareReq)
            @Html.ValidationMessageFor(model => model.SoftwareReq)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Limitations)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Limitations)
            @Html.ValidationMessageFor(model => model.Limitations)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "DashBoard")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QAServices/Accuracx/Views/UserProject/DashBoard.cshtml
@model IEnumerable<DBHandler.Model.Project>
@using GridMvc.Html

@{
    ViewBag.Title = "Listings";
}

<h2>@ViewBag.Title</h2>
<div class="clear-fix">&nbsp;</div>
<div class="btn btn-danger link-c-n">
    @Html.ActionLink("Create New", "Create")
</div>

<label>submited projects</label>@Model.Where(p => p.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.Submitted).Count();

<label>On going projects</label>@Model.Where(p => p.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.OnGoing).Count();

<label>Comleted  projects</label>@Model.Where(p => p.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.Complete).Count();

<label>New Bug Reports</label>@Model.Where(p => p.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.Complete).Count();

<label>Messages</label>@Model.Where(p => p.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.Complete).Count();

<h1>Submitted Projects</h1>

@Html.Grid(Model.Where(p=>p.StatusId==(int)DBHandler.Common.CommonEnums.ProjectStatus.Submitted)).Columns(columns =>
          {
              columns.Add(t => t.ProjectName).Titled("Project Name").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.ProjectType.ProjectTypeName).Titled("Project Type").SetWidth(120).Sortable(true).Filterable(true);

              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("View", "Details", "UserProject", new { id = o.ProjectId, page = ViewBag.Page }, new { @class = "btn btn-info modal-link" }).ToHtmlString());

          }).WithPaging(10)

<h1>Ongoing Projects</h1>

@Html.Grid(Model.Where(p=>p.StatusId==(int)DBHandler.Common.CommonEnums.ProjectStatus.OnGoing)).Columns(columns =>
          {
              columns.Add(t => t.ProjectName).Titled("Project Name").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.ProjectType.ProjectTypeName).Titled("Project Type").SetWidth(120).Sortable(true).Filterable(true);

              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("View", "Details", "UserProject", new { id = o.ProjectId, page = ViewBag.Page }, new { @class = "btn btn-info modal-link" }).ToHtmlString());

          }).WithPaging(10)

<h1>Completed Projects</h1>

@Html.Grid(Model.Where(p=>p.StatusId==(int)DBHandler.Common.CommonEnums.ProjectStatus.Complete)).Columns(columns =>
          {
              columns.Add(t => t.ProjectName).Titled("Project Name").SetWidth(120).Sortable(true).Filterable(true);
              columns.Add(t => t.ProjectType.ProjectTypeName).Titled("Project Type").SetWidth(120).Sortable(true).Filterable(true);

              columns.Add().Titled("").Sanitized(false).Encoded(false).RenderValueAs(o => Html.ActionLink("View", "Details", "UserProject", new { id = o.ProjectId, page = ViewBag.Page }, new { @class = "btn btn-info modal-link" }).ToHtmlString());

          }).WithPaging(10)

QAServices/Accuracx/Views/UserProject/Delete.cshtml
@model DBHandler.Model.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Project</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProjectType.ProjectTypeName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectType.ProjectTypeName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProjectName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Features)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Features)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HardwareReq)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HardwareReq)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.SoftwareReq)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SoftwareReq)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Limitations)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Limitations)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DocumentPath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DocumentPath)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.StatusId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StatusId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PaymentPlan.PaymentPlanName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PaymentPlan.PaymentPlanName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Quotation.Notes)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quotation.Notes)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProjectUrl)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectUrl)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

QAServices/Accuracx/Views/UserProject/Details.cshtml
@model DBHandler.Model.Project

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Project</legend>

    @Html.DisplayFor(model => model.ProjectName)

    @Html.Label((String)ViewBag.ProjectStatus)

    @Html.ActionLink("Notifications", "Index")

    @Html.ActionLink("Contact/Inquiry", "Index")

    @Html.Label((String)ViewBag.ClientMessage)

    @if (Model.StatusId == (int)DBHandler.Common.CommonEnums.ProjectStatus.Submitted)
    {
        if (Model.Quotation != null && Model.Quotation.Approved == true)
        {

        }
        else
        {
           @Html.Partial("BasicProjectDetails",Model)
        }
    }



    @*<div class="display-label">
         @Html.DisplayNameFor(model => model.DocumentPath)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DocumentPath)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.StatusId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.StatusId)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PaymentPlan.PaymentPlanName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PaymentPlan.PaymentPlanName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.User.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.User.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Quotation.Notes)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Quotation.Notes)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ProjectUrl)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ProjectUrl)
    </div>*@
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ProjectId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QAServices/Accuracx/Views/UserProject/Edit.cshtml
@model DBHandler.Model.Project

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Project</legend>

        @Html.HiddenFor(model => model.ProjectId)

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectTypeId, "ProjectType")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ProjectTypeId", String.Empty)
            @Html.ValidationMessageFor(model => model.ProjectTypeId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProjectName)
            @Html.ValidationMessageFor(model => model.ProjectName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Description)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Description)
            @Html.ValidationMessageFor(model => model.Description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Features)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Features)
            @Html.ValidationMessageFor(model => model.Features)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HardwareReq)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HardwareReq)
            @Html.ValidationMessageFor(model => model.HardwareReq)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SoftwareReq)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SoftwareReq)
            @Html.ValidationMessageFor(model => model.SoftwareReq)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Limitations)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Limitations)
            @Html.ValidationMessageFor(model => model.Limitations)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DocumentPath)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DocumentPath)
            @Html.ValidationMessageFor(model => model.DocumentPath)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StatusId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StatusId)
            @Html.ValidationMessageFor(model => model.StatusId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PaymentPlanId, "PaymentPlan")
        </div>
        <div class="editor-field">
            @Html.DropDownList("PaymentPlanId", String.Empty)
            @Html.ValidationMessageFor(model => model.PaymentPlanId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId, "User")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.QuotationId, "Quotation")
        </div>
        <div class="editor-field">
            @Html.DropDownList("QuotationId", String.Empty)
            @Html.ValidationMessageFor(model => model.QuotationId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ProjectUrl)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ProjectUrl)
            @Html.ValidationMessageFor(model => model.ProjectUrl)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QAServices/Accuracx/Views/UserProject/Index.cshtml
@model IEnumerable<DBHandler.Model.Project>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProjectType.ProjectTypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Features)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HardwareReq)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoftwareReq)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Limitations)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DocumentPath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StatusId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PaymentPlan.PaymentPlanName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quotation.Notes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProjectUrl)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProjectType.ProjectTypeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProjectName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Features)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HardwareReq)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoftwareReq)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Limitations)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DocumentPath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StatusId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PaymentPlan.PaymentPlanName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quotation.Notes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProjectUrl)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProjectId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProjectId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProjectId })
        </td>
    </tr>
}

</table>

QAServices/Accuracx/Views/UserProject/SubmittedProjectDetails.cshtml
@model DBHandler.Model.Project

@{
    ViewBag.Title = "Details";
}

<h1>project Details</h1>

@Html.DisplayFor(model => model.ProjectName)

@Html.Label((String)ViewBag.ProjectStatus)

@Html.ActionLink("Notifications", "Index")

@Html.ActionLink("Contact/Inquiry", "Index")

@Html.Label((String)ViewBag.ClientMessage)

<div class="display-label">
    @Html.DisplayNameFor(model => model.ProjectType.ProjectTypeName)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.ProjectType.ProjectTypeName)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.Description)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Description)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.Features)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Features)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.HardwareReq)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.HardwareReq)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.SoftwareReq)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.SoftwareReq)
</div>

<div class="display-label">
    @Html.DisplayNameFor(model => model.Limitations)
</div>
<div class="display-field">
    @Html.DisplayFor(model => model.Limitations)
</div>

@if (Model.Quotation != null)
{
    <h6>Quotation Details</h6>
    <label>Estimation</label>
    <label>@Model.Quotation.Estimation</label>
    <label>Budget</label>
    <label>@Model.Quotation.Budget</label>
    <label>Satus</label>
    if (!Model.Quotation.Approved)
    {
        <a href="#">Approve Quotation </a>
    }

}

<div>
    @Html.ActionLink("Back to List", "DashBoard")
</div>